# Generated by Django 3.1 on 2020-10-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstyle',
            name='style',
            field=models.CharField(choices=[('V', 'VISUAL'), ('A', 'AUDITORY'), ('MM', 'MULTIMODAL')], max_length=5),
        ),
    ]
