# Generated by Django 3.1 on 2020-10-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0004_auto_20201008_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarionum', models.IntegerField()),
                ('scenario', models.CharField(max_length=150)),
                ('question', models.CharField(max_length=150)),
                ('ltype', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='learningstyle',
            name='auditoryscore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningstyle',
            name='kinestheticscore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningstyle',
            name='readingscore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningstyle',
            name='visualscore',
            field=models.FloatField(default=0),
        ),
    ]
