# Generated by Django 3.1 on 2020-10-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0005_auto_20201014_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningassessment',
            old_name='question',
            new_name='auditoryquestion',
        ),
        migrations.RemoveField(
            model_name='learningassessment',
            name='ltype',
        ),
        migrations.AddField(
            model_name='learningassessment',
            name='kinestheticquestion',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningassessment',
            name='readingquestion',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningassessment',
            name='visualquestion',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
