# Generated by Django 3.1 on 2020-10-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0007_baseskill_multiplechoice_shortanswer_userreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreports',
            name='q1posttestscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreports',
            name='q1pretestscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreports',
            name='q2posttestscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreports',
            name='q2pretestscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreports',
            name='q3posttestscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreports',
            name='q3pretestscore',
            field=models.IntegerField(default=0),
        ),
    ]
