# Generated by Django 3.1 on 2020-10-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0008_auto_20201023_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseskill',
            name='keyword',
            field=models.CharField(default='', max_length=20),
        ),
    ]
