# Generated by Django 3.1 on 2020-10-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0009_baseskill_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstyle',
            name='auditorypercent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningstyle',
            name='kinestheticpercent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningstyle',
            name='readingpercent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningstyle',
            name='visualpercent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='learningstyle',
            name='auditoryscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningstyle',
            name='kinestheticscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningstyle',
            name='readingscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningstyle',
            name='visualscore',
            field=models.IntegerField(default=0),
        ),
    ]
