# Generated by Django 3.1 on 2020-11-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0010_auto_20201030_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('imgurl', models.CharField(max_length=300)),
                ('qtype', models.CharField(max_length=30)),
                ('first', models.CharField(max_length=300)),
                ('second', models.CharField(max_length=300)),
                ('third', models.CharField(max_length=300)),
                ('fourth', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulltma.baseskill')),
            ],
        ),
        migrations.RemoveField(
            model_name='shortanswer',
            name='skill',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='ShortAnswer',
        ),
    ]
