# Generated by Django 3.1 on 2020-11-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0013_auto_20201109_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='pfp',
            field=models.ImageField(default='ulltma/pfp/default.png', upload_to='ulltma/pfp'),
        ),
    ]
