# Generated by Django 3.1 on 2020-11-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0014_auto_20201109_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('V', 'VISUAL'), ('A', 'AUDITORY'), ('R', 'READING / WRITING'), ('K', 'KINESTHETIC'), ('M', 'MULTIMODAL')], max_length=25)),
                ('url', models.CharField(max_length=300)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulltma.baseskill')),
            ],
        ),
    ]
