# Generated by Django 3.1 on 2020-12-16 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0017_auto_20201118_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_clicked', to='ulltma.learningtool')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_clicked', to='ulltma.learningtool')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulltma.learningtool')),
            ],
        ),
    ]
