# Generated by Django 3.1 on 2020-12-16 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0018_clickedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickedlink',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_clicked', to='ulltma.baseskill'),
        ),
        migrations.AlterField(
            model_name='clickedlink',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
