# Generated by Django 3.1 on 2020-12-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0019_auto_20201216_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickedlink',
            name='modality',
            field=models.CharField(max_length=25),
        ),
    ]
