# Generated by Django 3.1 on 2020-12-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0020_auto_20201216_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickedlink',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
