# Generated by Django 3.1 on 2021-01-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0022_auto_20201216_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltestquestions',
            name='first',
        ),
        migrations.RemoveField(
            model_name='skilltestquestions',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='skilltestquestions',
            name='qtype',
        ),
        migrations.RemoveField(
            model_name='skilltestquestions',
            name='second',
        ),
        migrations.RemoveField(
            model_name='skilltestquestions',
            name='third',
        ),
    ]
