# Generated by Django 3.1 on 2021-01-28 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0023_auto_20210115_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreports',
            name='finishdate',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
