# Generated by Django 3.1 on 2021-02-01 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0024_userreports_finishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstyle',
            name='datetaken',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
