# Generated by Django 3.1 on 2021-02-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0025_learningstyle_datetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstyle',
            name='datetaken',
            field=models.DateField(null=True),
        ),
    ]
