# Generated by Django 3.1 on 2021-02-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0027_userreports_posttestavg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortdesc', models.CharField(default='', max_length=500)),
                ('longdesc', models.CharField(default='', max_length=1500)),
                ('issuedate', models.DateField()),
            ],
        ),
    ]
