# Generated by Django 3.1 on 2021-03-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0028_appissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtool',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
