# Generated by Django 3.1 on 2021-03-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0029_learningtool_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtool',
            name='viability',
            field=models.CharField(choices=[('V', 'VISUAL'), ('A', 'AUDITORY'), ('R', 'READING / WRITING'), ('K', 'KINESTHETIC'), ('M', 'MULTIMODAL')], default='VB', max_length=25),
        ),
    ]
