# Generated by Django 3.1 on 2021-07-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0031_auto_20210716_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreports',
            name='style',
            field=models.CharField(default='VISUAL', max_length=20),
        ),
    ]
