# Generated by Django 3.1 on 2021-08-17 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0032_auto_20210726_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=2000)),
                ('imgurl', models.CharField(max_length=300)),
                ('op1', models.CharField(max_length=2000)),
                ('op2', models.CharField(max_length=2000)),
                ('op3', models.CharField(max_length=2000)),
                ('op4', models.CharField(max_length=2000)),
                ('op5', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=300)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulltma.baseskill')),
            ],
        ),
        migrations.DeleteModel(
            name='SkillTestQuestions',
        ),
    ]
