# Generated by Django 3.1 on 2021-08-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0033_auto_20210817_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltestquestion',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
