# Generated by Django 3.1 on 2021-10-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0038_auto_20211005_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltestquestion',
            name='imgurl',
            field=models.CharField(default='-', max_length=50000),
        ),
        migrations.AlterField(
            model_name='skilltestquestion',
            name='op1',
            field=models.CharField(default='-', max_length=50000),
        ),
        migrations.AlterField(
            model_name='skilltestquestion',
            name='op2',
            field=models.CharField(default='-', max_length=50000),
        ),
        migrations.AlterField(
            model_name='skilltestquestion',
            name='op3',
            field=models.CharField(default='-', max_length=50000),
        ),
        migrations.AlterField(
            model_name='skilltestquestion',
            name='op4',
            field=models.CharField(default='-', max_length=50000),
        ),
        migrations.AlterField(
            model_name='skilltestquestion',
            name='op5',
            field=models.CharField(default='-', max_length=50000),
        ),
    ]
