# Generated by Django 3.1 on 2021-10-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0039_auto_20211005_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltestquestion',
            name='op6',
            field=models.CharField(default='-', max_length=50000),
        ),
    ]
