# Generated by Django 3.1 on 2021-10-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0040_skilltestquestion_op6'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltestquestion',
            name='imgfile',
            field=models.ImageField(default='-', upload_to='ulltma/test question pics'),
        ),
    ]
