# Generated by Django 3.1 on 2021-10-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0041_skilltestquestion_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltestquestion',
            name='imgfile',
            field=models.ImageField(default='-', upload_to='tqpics'),
        ),
    ]
