# Generated by Django 3.1 on 2021-10-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0042_auto_20211006_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltestquestion',
            name='op1img',
            field=models.ImageField(default='-', upload_to='op1pics'),
        ),
        migrations.AddField(
            model_name='skilltestquestion',
            name='op2img',
            field=models.ImageField(default='-', upload_to='op2pics'),
        ),
        migrations.AddField(
            model_name='skilltestquestion',
            name='op3img',
            field=models.ImageField(default='-', upload_to='op3pics'),
        ),
        migrations.AddField(
            model_name='skilltestquestion',
            name='op4img',
            field=models.ImageField(default='-', upload_to='op4pics'),
        ),
        migrations.AddField(
            model_name='skilltestquestion',
            name='op5img',
            field=models.ImageField(default='-', upload_to='op5pics'),
        ),
        migrations.AddField(
            model_name='skilltestquestion',
            name='op6img',
            field=models.ImageField(default='-', upload_to='op6pics'),
        ),
    ]
