# Generated by Django 3.1 on 2021-11-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0044_auto_20211119_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltestquestion',
            name='qtype',
            field=models.CharField(choices=[('shortanswer', 'shortanswer'), ('longanswer', 'longanswer'), ('multoptions', 'multoptions'), ('graph', 'graph'), ('numberline', 'numberline'), ('geometry', 'geometry'), ('geomultoptions', 'geomultoptions')], max_length=20),
        ),
    ]
