# Generated by Django 3.1 on 2022-01-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0045_auto_20211119_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickedLink',
        ),
    ]
