# Generated by Django 3.1 on 2022-02-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0047_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_secret',
            field=models.CharField(max_length=32),
        ),
    ]
