# Generated by Django 3.1 on 2022-03-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0050_auto_20220308_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_time_taken_modality_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_secret',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
