# Generated by Django 4.0.3 on 2022-04-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0051_auto_20220314_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_email_notif',
            field=models.BooleanField(default=True),
        ),
    ]
