# Generated by Django 4.0.3 on 2022-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0052_profile_receive_email_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='default_preference',
            field=models.CharField(choices=[('default 1', 'default1'), ('default 2', 'default2'), ('default 3', 'default3'), ('default 4', 'default4')], default='default 1', max_length=20),
        ),
    ]
