# Generated by Django 4.0.3 on 2022-05-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulltma', '0053_profilepicture_default_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='default_preference',
            field=models.CharField(choices=[('default1', 'default 1'), ('default2', 'default 2'), ('default3', 'default 3'), ('default4', 'default 4')], default='default 1', max_length=20),
        ),
    ]
